server:
  port: 8085

spring:
  data:
    mongodb:
      username: root
      password: rootpassword
      database: product_db
      host: localhost
      port: 27017
      authentication-database: admin

grpc:
  server:
    port: 9050
    reflection-service-enabled: true